---
- name: Hello
  shell: "echo hello"
  tags:
    - hello

- name: Bye
  shell: "echo bye"
  tags:
    - bye
    
- debug:
    msg: "{{ APP }}"
    
- debug:
    msg: "{{ APP }}"
    
- debug:
    msg: "{{ APP }}"
