---
- name: Hello
  shell: "echo hello"
  tags:
    - hello

- name: Bye
  shell: "echo bye"
  tags:
    - bye
    
- debug:
    msg: "{{ test1 }}"
    
- debug:
    msg: "{{ test2 }}"
    
- debug:
    msg: "{{ test3 }}"
